version: "3.7"

services:
    server:
        build: ./server
        mem_limit: 512m
        mem_reservation: 128M
        cpus: 0.1
        ports:
            - 7001:7001
        expose:
            - 7001
        links:
            - puyo_server
        
    app:
        build: ./app
        ports:
            - 7000:7000
        expose:
            - 7000
        cpus: 0.3
